# Používateľské rozhranie
Súbor: user.ipynb

Program: Hospodárska informatika

Vypracovala: Bc. Veronika Motúzová

Diplomová práca: : Predikcia geomagnetickych búrok pomocou hlbokého učenia

Vedúci diplomovej práce: doc. Ing. Peter Butka, PhD.

Konzultanti: Ing. Viera Maslej Krešňáková, PhD., RNDr. Šimon Mackovjak, PhD. 

In [26]:
from tensorflow import keras
from keras.preprocessing.sequence import TimeseriesGenerator
from keras.models import Model
import numpy as np

### Model iba s použitím DST indexu

In [19]:
DST = [-10,13,16,-20,-25,-40,-30] # používateľ zadá sekvenciu aspoň 7 historických hodnôt DST indexu

In [20]:
generator = TimeseriesGenerator(DST, [0,0,0,0,0,0,0], length=6, batch_size=256)

In [21]:
model = keras.models.load_model('6_dozadu_6_dopredu.hdf5')

In [22]:
DST_6 = model.predict(generator)

1/1 [==============================] - 0s 490ms/step


In [23]:
print(DST_6) #predikovaný DST index s predstihom 6 hodín

[[-10.165003]]


### Model s použitím 3 atribútov DST, F10_INDEX a BZ_GSM

In [46]:
DST = np.array([[-10],[13],[16],[-20],[-25],[-40],[-30]]) # používateľ zadá sekvenciu aspoň 7 historických hodnôt všetkých 3 atribútov
F10_INDEX = np.array([[177.69],[177.69],[178.39],[178.39],[178.39],[178.39],[178.39]])
BZ_GSM = np.array([[1.79],[2.29],[1.60],[1.29],[1.89],[3.20],[0.40]])

inputs = np.concatenate((DST, F10_INDEX, BZ_GSM), axis=1)

In [47]:
print(inputs)

[[-10.   177.69   1.79]
 [ 13.   177.69   2.29]
 [ 16.   178.39   1.6 ]
 [-20.   178.39   1.29]
 [-25.   178.39   1.89]
 [-40.   178.39   3.2 ]
 [-30.   178.39   0.4 ]]


In [48]:
generator = TimeseriesGenerator(inputs, [0,0,0,0,0,0,0], length=6, batch_size=256)

In [49]:
model = keras.models.load_model('6_6_pridane_atr.hdf5')

In [50]:
DST_6 = model.predict(generator)

1/1 [==============================] - 1s 505ms/step


In [51]:
print(DST_6) #predikovaný DST index s predstihom 6 hodín

[[-9.2008295]]
